### ISSUE TITLE
npm run start doesn't work (demo)

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebulagraph-veditor#25]
We followed the [documentation](https://github.com/vesoft-inc/nebulagraph-veditor)

- Open terminal
- npm install @vesoft-inc/veditor --save
```
npm WARN saveError ENOENT: no such file or directory, open '/mnt/c/tobedeleted/veditor/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for canvg@4.0.1: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: canvg@4.0.1
npm WARN notsup Unsupported engine for svg-pathdata@6.0.3: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: svg-pathdata@6.0.3
npm WARN enoent ENOENT: no such file or directory, open '/mnt/c/tobedeleted/veditor/package.json'
npm WARN veditor No description
npm WARN veditor No repository field.
npm WARN veditor No README data
npm WARN veditor No license field.

+ @vesoft-inc/veditor@4.3.3-beta.2
added 14 packages from 20 contributors and audited 14 packages in 4.331s
found 0 vulnerabilities
```
-- ls
```
admin@DESKTOP-RMGSJKG:/mnt/c/tobedeleted/veditor$ ls
node_modules  package-lock.json
```
-- npm run start
```
admin@DESKTOP-RMGSJKG:/mnt/c/tobedeleted/veditor$ npm run start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /mnt/c/tobedeleted/veditor/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/mnt/c/tobedeleted/veditor/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ramsun/.npm/_logs/2022-09-19T20_06_30_276Z-debug.log
```

**Comment by mizy** [comment]
try to use yarn install?

**Comment by porscheme** [comment]
> you need to clone the repo first then
> 
> ```
> npm install 
> npm run start
> ```

Yes, we did clone the repo and then 'npm install' and 'npm run start'. Below  is the complete terminal output.

```
npm install
npm WARN babel-loader@8.2.5 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN css-loader@1.0.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN less-loader@4.1.0 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN typedoc-theme-stacks@1.0.0 requires a peer of typedoc@^0.22.11 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@1.1.2 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 529 packages in 112.202s

45 packages are looking for funding
  run `npm fund` for details

found 6 vulnerabilities (2 low, 2 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
admin@DESKTOP-RMGSJKG:/mnt/c/tobedeleted/nebulagraph-veditor$ npm audit fix
npm WARN babel-loader@8.2.5 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN css-loader@1.0.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN less-loader@4.1.0 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN typedoc-theme-stacks@1.0.0 requires a peer of typedoc@^0.22.11 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@1.1.2 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 21.621s

45 packages are looking for funding
  run `npm fund` for details

fixed 0 of 6 vulnerabilities in 529 scanned packages
  2 package updates for 6 vulnerabilities involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
admin@DESKTOP-RMGSJKG:/mnt/c/tobedeleted/nebulagraph-veditor$ npm audit fix --force
npm WARN using --force I sure hope you know what you are doing.
npm WARN babel-loader@8.2.5 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN less-loader@4.1.0 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN typedoc-theme-stacks@1.0.0 requires a peer of typedoc@^0.22.11 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@1.1.2 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

+ css-loader@6.7.1
+ antd@4.23.2
added 23 packages from 56 contributors, removed 78 packages and updated 41 packages in 686.653s

48 packages are looking for funding
  run `npm fund` for details

fixed 6 of 6 vulnerabilities in 529 scanned packages
  2 package updates for 6 vulnerabilities involved breaking changes
  (installed due to `--force` option)
admin@DESKTOP-RMGSJKG:/mnt/c/tobedeleted/nebulagraph-veditor$ npm run start

> @vesoft-inc/veditor@4.3.2 start /mnt/c/tobedeleted/nebulagraph-veditor
> webpack serve

[webpack-cli] /mnt/c/tobedeleted/nebulagraph-veditor/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:10
  static heartbeatInterval = 1000;
                           ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Server.getServerTransport (/mnt/c/tobedeleted/nebulagraph-veditor/node_modules/webpack-dev-server/lib/Server.js:1685:28)
    at Server.createWebSocketServer (/mnt/c/tobedeleted/nebulagraph-veditor/node_modules/webpack-dev-server/lib/Server.js:2484:57)
    at Server.start (/mnt/c/tobedeleted/nebulagraph-veditor/node_modules/webpack-dev-server/lib/Server.js:3277:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @vesoft-inc/veditor@4.3.2 start: `webpack serve `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @vesoft-inc/veditor@4.3.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/admin/.npm/_logs/2022-09-21T18_19_48_868Z-debug.log
```

**Comment by mizy** [comment]
ok ,that's a bug, i will fix it ,thank you
